### ISSUE TITLE
Bookmark

### ISSUE THREAD

**Issue by SabSchek** [SabSchek/capstone-project#11]
Value Proposition
As a User I need bookmarks to be able to save the items I like on a different page. 

Description
<img width="199" alt="Bildschirmfoto 2022-10-05 um 09 50 40" src="https://user-images.githubusercontent.com/109827469/194008545-5e2a849b-8ea4-4adc-9219-bff383394fc1.png">

Acceptance Criteria
 - [ ] after clicking the bookmark, the articles is displayed on the bookmarks page
 - [ ]   if bookmark page is empty, a info text is displayed
 

Tasks
- [ ] new branch
- [ ] component bookmark / toggle function
- [ ] function to render cards on bookmark page
- [ ] set basic styling

**Comment by MerleMak** [comment]
Hi Fine, nice User story!

I would write the Value Proposition and the AC a little less technical. What I mean is:
VP:
"As a User I need bookmarks to be able to save my favourite items."

AC:
- [ ] after clicking the bookmark, the articles is displayed on the bookmarks page
- [ ] if bookmark page is empty, a picture is displayed -> (maybe an informative text like "You can save your favourite items and access them here", or something similar would be more helpful to the user than a picture?)

you can delete  "describe every scenario in detail" as it is only an instruction on the template :)
I am exited to see this story being build! 🤩

**Comment by SabSchek** [comment]
thanks @MerleMak, that's a great feedback!
